# Generated by Django 5.0.2 on 2024-04-29 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_a_period_1', models.IntegerField(default=1000)),
                ('day_a_period_2', models.IntegerField(default=1000)),
                ('day_a_period_3', models.IntegerField(default=1000)),
                ('day_a_period_4', models.IntegerField(default=1000)),
                ('day_b_period_1', models.IntegerField(default=1000)),
                ('day_b_period_2', models.IntegerField(default=1000)),
                ('day_b_period_3', models.IntegerField(default=1000)),
                ('day_b_period_4', models.IntegerField(default=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
