# Generated by Django 5.0.4 on 2024-05-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roominput',
            name='grade_level',
            field=models.IntegerField(default=9),
        ),
    ]
