# Generated by Django 5.0.4 on 2024-05-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_map', '0002_roominput_grade_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roominput',
            name='grade_level',
            field=models.IntegerField(),
        ),
    ]
