# Generated by Django 5.0.4 on 2024-05-07 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_map', '0003_alter_roominput_grade_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roominput',
            name='grade_level',
        ),
    ]
